sudo: required
services:
  - docker
language: go
go:
  - "1.11"
env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - docker-ce

script:
  - chmod +x ./build.sh && ./build.sh

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/xuchengpeng/gohttpserver.git

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
